#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    # was the program called correctly?
    if(len(sys.argv) != 2):
        sys.exit("usage: ./tweets handle")
        
    # call twitter API and clean up the handle if necessary
    handle = sys.argv[1].strip('@')
    userTweets = helpers.get_user_timeline(handle,100)
    
    if userTweets == None:
        sys.exit("dude... no tweets found!")
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # analyze tweet
    for tweet in userTweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(f"{score} {tweet}", "green"))
        elif score < 0.0:
            print(colored(f"{score} {tweet}", "red"))
        else:
            print(colored(f"{score} {tweet}", "yellow"))        
    
    
if __name__ == "__main__":
    main()